version: "2"
services:
  web:
    stdin_open: true
    tty: true
    image: sebp/lighttpd
    container_name: lerpy-rotate
    restart: always
    volumes:
      - ./:/var/www/localhost/htdocs
      - ./data:/var/www/html/data
    ports:
      - ${APACHE_PORT}:80
